### ISSUE TITLE
postgres db provide the connection with port: 5432 at suffix of the the env, but given port number not in the connected project env

### ISSUE THREAD

**Issue by coolbii** [vercel/storage#373]
I think there are two issues:
1. as I mentioned in title, I'm not sure is there difference that connet to a db with port number or not

when create a new one vercel PG db: you provide like POSTGRES_URL="xxxx.vercel-storage.com:5432/verceldb"

but when I click connect project button to bind to another vercel project

you provide POSTGRES_URL="xxxx.vercel-storage.com/verceldb"  (! NOTICE ! no port number)

2. Currently I'm connecting Vercel PG DB to another project that uses NestJS with graphql ( also hosted on Vercel )

and when I write
```
this.prisma.article.findUniqueOrThrow({ 
   where: {
      id,
 }
```

it frequently will throws errors like:
```
Invalid `prisma.article.findUniqueOrThrow()` invocation:
Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState(E42P05), message: "prepared statement \"s9\" already exists", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("prepare.c"), line: Some(412), routine: Some("StorePreparedStatement") }) }), transient: false })[39m
PrismaClientUnknownRequestError: 
Invalid `prisma.article.findUniqueOrThrow()` invocation:
Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState(E42P05), message: "prepared statement \"s9\" already exists", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("prepare.c"), line: Some(412), routine: Some("StorePreparedStatement") }) }), transient: false })
at vn.handleRequestError (/var/task/node_modules/@prisma/client/runtime/library.js:123:6902)
at vn.handleAndLogRequestError (/var/task/node_modules/@prisma/client/runtime/library.js:123:6119)
at vn.request (/var/task/node_modules/@prisma/client/runtime/library.js:123:5839)
at l (/var/task/node_modules/@prisma/client/runtime/library.js:128:9763)
at /var/task/node_modules/@prisma/client/runtime/library.js:34:549
at target (/var/task/node_modules/@nestjs/core/helpers/external-context-creator.js:74:28)
at Object.article (/var/task/node_modules/@nestjs/core/helpers/external-proxy.js:9:24)
```

similar issue has been raised on Prisma repo for many times, I'm not sure does the issue (1) I point out has something to do with the issue (2)

**Comment by adriancooney** [comment]
Hi @ntubrian, thanks for the report. It is true that the UI will show the port and the environment variables will omit it but both variants work fine so there should be no issue. If the port is omitted, the default port of `5432` should be used.

```sh
$ psql "postgres://default:<snip>@<snip>.us-east-1.postgres.vercel-storage.com:5432/verceldb"
psql (14.7 (Homebrew), server 15.4)
WARNING: psql major version 14, server major version 15.
         Some psql features might not work.
SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, bits: 256, compression: off)
Type "help" for help.

verceldb=> \q
$ psql "postgres://default:<snip>@<snip>.us-east-1.postgres.vercel-storage.com/verceldb"
psql (14.7 (Homebrew), server 15.4)
WARNING: psql major version 14, server major version 15.
         Some psql features might not work.
SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, bits: 256, compression: off)
Type "help" for help.

verceldb=> \q
```

For the Prisma `prepared statement \"s*\" already exists` error, that's typically caused by connecting directly to the database instead of using the connection pooler. You can connect using the connection pooler in Prisma by using the  `POSTGRES_PRISMA_URL` environment variable which has the format `postgres://default:<snip>@<snip>.us-east-1.postgres.vercel-storage.com:5432/verceldb?pgbouncer=true&connect_timeout=15`. Your Prisma config should look like:

```
datasource db {
  provider = "postgresql"
  url = env("POSTGRES_PRISMA_URL") // uses connection pooling
  directUrl = env("POSTGRES_URL_NON_POOLING") // uses a direct connection
}
```

Let me know if that solves your problem. If it doesn't, please re-open the issue. Thanks!
