### ISSUE TITLE
@vercel/blob – Uploading a file starting with a URL-encoded string fails during (browser) upload 

### ISSUE THREAD

**Issue by mfts** [vercel/storage#442]
file name: `%F0%9F%92%8Dpresentation-compressed.pdf`

Getting the following console error 

```
chunk-NT5X67TN.js:132 
        
PUT https://blob.vercel-storage.com/%F0%9F%92%8Dpresentation-compressed.pdf 403 (Forbidden)
put @ chunk-NT5X67TN.js:132
await in put (async)
handleBrowserUpload @ add-document-modal.tsx:39
callCallback @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:4291
executeDispatch @ react-dom.development.js:9041
processDispatchQueueItemsInOrder @ react-dom.development.js:9073
processDispatchQueue @ react-dom.development.js:9086
dispatchEventsForPlugins @ react-dom.development.js:9097
eval @ react-dom.development.js:9288
batchedUpdates$1 @ react-dom.development.js:26140
batchedUpdates @ react-dom.development.js:3991
dispatchEventForPluginEventSystem @ react-dom.development.js:9287
dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay @ react-dom.development.js:6465
dispatchEvent @ react-dom.development.js:6457
dispatchDiscreteEvent @ react-dom.development.js:6430

client.js:1 

An error occurred while uploading the file:  Error: Vercel Blob: Access denied, please provide a valid token for this resource
    at validateBlobApiResponse (chunk-NT5X67TN.js:60:1)
    at async put (chunk-NT5X67TN.js:140:1)
    at async handleBrowserUpload (add-document-modal.tsx:39:23)
```

**Comment by correttojs** [comment]
hey @mfts , thanks for reporting the issue, indeed I was able to reproduce it. 
Will look into it and provide a fix soon!

**Comment by mfts** [comment]
Thanks Fabio

**Comment by luismeyer** [comment]
Hey @mfts 👋 , 
we just released a new blob API version with a fix that allows URL encoded characters in the pathname of `put` operations. No code changes should be needed. If it still doesn't work on your side please reach out 👍

**Comment by mfts** [comment]
Thanks @luismeyer for the follow-up. Will update to the latest version :)
