### ISSUE TITLE
@vercel/blob - client uploads fails for large file sizes

### ISSUE THREAD

**Issue by mfts** [vercel/storage#443]
According to the docs, client uploads work with up to 500MB files. I tried to upload a 128MB file and keep getting an error from vercel. 

Is there a way to debug this? 

```
chunk-NT5X67TN.js:132 
        
PUT https://blob.vercel-storage.com/Keeper.pdf 403 (Forbidden)
put @ chunk-NT5X67TN.js:132
await in put (async)
handleBrowserUpload @ add-document-modal.tsx:39
callCallback @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:4291
executeDispatch @ react-dom.development.js:9041
processDispatchQueueItemsInOrder @ react-dom.development.js:9073
processDispatchQueue @ react-dom.development.js:9086
dispatchEventsForPlugins @ react-dom.development.js:9097
eval @ react-dom.development.js:9288
batchedUpdates$1 @ react-dom.development.js:26140
batchedUpdates @ react-dom.development.js:3991
dispatchEventForPluginEventSystem @ react-dom.development.js:9287
dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay @ react-dom.development.js:6465
dispatchEvent @ react-dom.development.js:6457
dispatchDiscreteEvent @ react-dom.development.js:6430

client.js:1 

An error occurred while uploading the file:  Error: Vercel Blob: Access denied, please provide a valid token for this resource
    at validateBlobApiResponse (chunk-NT5X67TN.js:60:1)
    at async put (chunk-NT5X67TN.js:140:1)
    at async handleBrowserUpload (add-document-modal.tsx:39:23)

**Comment by correttojs** [comment]
hi @mfts, could you share your `handleUpload` code? Does the upload fail consistently? Have you tried uploading smaller files? From the error message it seems there is something wrong with the token you are sending

**Comment by mfts** [comment]
it works just fine on smaller sizes. I haven't found the exact limit where it breaks. typically I'm uploading 30MB files, but there a usecase for a single >100MB file. 


```ts
import { handleUpload, type HandleUploadBody } from "@vercel/blob/client";
import type { NextApiResponse, NextApiRequest } from "next";
import { getServerSession } from "next-auth/next";
import { authOptions } from "../auth/[...nextauth]";
import { CustomUser } from "@/lib/types";

export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse
) {
  const body = JSON.parse(req.body) as HandleUploadBody;

  try {
    const jsonResponse = await handleUpload({
      body,
      request: req,
      onBeforeGenerateToken: async (pathname: string) => {
        // Generate a client token for the browser to upload the file

        const session = await getServerSession(req, res, authOptions);
        if (!session) {
          res.status(401).end("Unauthorized");
          throw new Error("Unauthorized");
        }

        return {
          allowedContentTypes: ["application/pdf"],
          maximumSizeInBytes: 200 * 1024 * 1024, // I temporarily increased this locally when testing the >100 MB file
          metadata: JSON.stringify({
            // optional, sent to your server on upload completion
            userId: (session.user as CustomUser).id,
          }),
        };
      },
      onUploadCompleted: async ({ blob, tokenPayload }) => {
        // Get notified of browser upload completion
        // ⚠️ This will not work on `localhost` websites,
        // Use ngrok or similar to get the full upload flow

        console.log("blob upload completed", blob, tokenPayload);

        try {
          // Run any logic after the file upload completed
          // const { userId } = JSON.parse(tokenPayload);
          // await db.update({ avatar: blob.url, userId });
        } catch (error) {
          // throw new Error("Could not update user");
        }
      },
    });

    return res.status(200).json(jsonResponse);
  } catch (error) {
    // The webhook will retry 5 times waiting for a 200
    return res.status(400).json({ error: (error as Error).message });
  }
}
```

**Comment by correttojs** [comment]
Your code looks good (and if it works with smaller files it should work for any). 
I just tested the upload of some big files (about 128Mb) setting the `maximumSizeInBytes: 200_000_000` without facing any issue. 
Could you please share your storeId so I can check our logs?

**Comment by correttojs** [comment]
hey @mfts, we may have found the issue: the token has a default expiration of 30s, which means it may be expired by the time the file upload completes and the token gets validated. 

Could you try setting a longer expiration through the `validUntil` field? See https://vercel.com/docs/storage/vercel-blob/using-blob-sdk#client-uploads-routes for additional details about its usage.

Thanks @luismeyer for spotting the issue!

**Comment by mfts** [comment]
Thanks for quick reply. You guys are awesome! That was indeed the error. 

I increased the expiration `validUntil` and it worked! 

Thank you @correttojs and @luismeyer 

Closing the issue as resolved :)

**Comment by vvo** [comment]
Oh that's right, and because we're buffering the whole body before validating the token then by the time we have the whole file then the token expired. We'll see how to make this better. 👍

**Comment by abdullahhsajid** [comment]
google/
