### ISSUE TITLE
@vercel/postgres error: Prepared statement does not exist

### ISSUE THREAD

**Issue by johnsimeroth** [vercel/storage#446]
Received the "prepared statement does not exist" error (full error log at bottom of post) while using vercel provided code (from Learn Next.js course, specifically [here](https://nextjs.org/learn/dashboard-app/setting-up-your-database#seed-your-database)). What's baffling is the SQL provided by vercel looks correct to me (copied below), and mostly works, but fails on a random index *only* for Invoices and Revenue. Every time I run the script it successfully seeds some number of Invoices and then fails on a random index. Same is true if I run it for revenue. Customers and Users get seeded properly without issue. 

Here's the table schema and insert statements for invoices, as an example:
```js
async function seedInvoices() {
  await sql`CREATE EXTENSION IF NOT EXISTS "uuid-ossp"`;

  const createTable = await sql`
    CREATE TABLE IF NOT EXISTS invoices (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    customer_id UUID NOT NULL,
    amount INT NOT NULL,
    status VARCHAR(255) NOT NULL,
    date DATE NOT NULL
  );
`;

  const insertedInvoices = await Promise.all(
    invoices.map(
      (invoice, i) => sql`
        INSERT INTO invoices (customer_id, amount, status, date)
        VALUES (${invoice.customer_id}, ${invoice.amount}, ${invoice.status}, ${invoice.date})
        ON CONFLICT (id) DO NOTHING;
      `
    )
  );
}
```

Here are the seed data for invoices:
```js
const invoices = [
  {
    customer_id: '3958dc9e-712f-4377-85e9-fec4b6a6442a',
    amount: 15795,
    status: 'pending',
    date: '2022-12-06'
  },
  {
    customer_id: '3958dc9e-742f-4377-85e9-fec4b6a6442a',
    amount: 20348,
    status: 'pending',
    date: '2022-11-14'
  },
  {
    customer_id: '3958dc9e-787f-4377-85e9-fec4b6a6442a',
    amount: 3040,
    status: 'paid',
    date: '2022-10-29'
  },
  {
    customer_id: '50ca3e18-62cd-11ee-8c99-0242ac120002',
    amount: 44800,
    status: 'paid',
    date: '2023-09-10'
  },
  {
    customer_id: '76d65c26-f784-44a2-ac19-586678f7c2f2',
    amount: 34577,
    status: 'pending',
    date: '2023-08-05'
  },
  {
    customer_id: '126eed9c-c90c-4ef6-a4a8-fcf7408d3c66',
    amount: 54246,
    status: 'pending',
    date: '2023-07-16'
  },
  {
    customer_id: 'd6e15727-9fe1-4961-8c5b-ea44a9bd81aa',
    amount: 666,
    status: 'pending',
    date: '2023-06-27'
  },
  {
    customer_id: '50ca3e18-62cd-11ee-8c99-0242ac120002',
    amount: 32545,
    status: 'paid',
    date: '2023-06-09'
  },
  {
    customer_id: '3958dc9e-787f-4377-85e9-fec4b6a6442a',
    amount: 1250,
    status: 'paid',
    date: '2023-06-17'
  },
  {
    customer_id: '76d65c26-f784-44a2-ac19-586678f7c2f2',
    amount: 8546,
    status: 'paid',
    date: '2023-06-07'
  },
  {
    customer_id: '3958dc9e-742f-4377-85e9-fec4b6a6442a',
    amount: 500,
    status: 'paid',
    date: '2023-08-19'
  },
  {
    customer_id: '76d65c26-f784-44a2-ac19-586678f7c2f2',
    amount: 8945,
    status: 'paid',
    date: '2023-06-03'
  },
  {
    customer_id: '3958dc9e-737f-4377-85e9-fec4b6a6442a',
    amount: 8945,
    status: 'paid',
    date: '2023-06-18'
  },
  {
    customer_id: '3958dc9e-712f-4377-85e9-fec4b6a6442a',
    amount: 8945,
    status: 'paid',
    date: '2023-10-04'
  },
  {
    customer_id: '3958dc9e-737f-4377-85e9-fec4b6a6442a',
    amount: 1000,
    status: 'paid',
    date: '2022-06-05'
  }
]
```

Here are some typical error logs:
```bash
Error seeding invoices: NeonDbError: db error: ERROR: prepared statement "s6495894" does not exist

Caused by:
    ERROR: prepared statement "s6495894" does not exist
    at execute (/Users/johnathansimeroth/Documents/sweProjects/nextjs-dashboard/node_modules/@neondatabase/serverless/index.js:1539:48)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 7)
    at async seedInvoices (/Users/johnathansimeroth/Documents/sweProjects/nextjs-dashboard/scripts/seed.js:79:30)
    at async /Users/johnathansimeroth/Documents/sweProjects/nextjs-dashboard/scripts/seed.js:182:3 {
  code: '26000',
  sourceError: undefined
}
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
```

My system info from `npx envinfo`:
```bash
System:
    OS: macOS 14.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 936.34 MB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 21.1.0 - ~/.nvm/versions/node/v21.1.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v21.1.0/bin/yarn
    npm: 10.2.1 - ~/.nvm/versions/node/v21.1.0/bin/npm
    pnpm: 8.10.0 - ~/.nvm/versions/node/v21.1.0/bin/pnpm
  Browsers:
    Chrome: 118.0.5993.117
    Safari: 17.1
  npmPackages:
    @heroicons/react: ^2.0.18 => 2.0.18 
    @tailwindcss/forms: ^0.5.6 => 0.5.6 
    @types/bcrypt: ^5.0.1 => 5.0.1 
    @types/node: 20.5.7 => 20.5.7 
    @types/react: 18.2.21 => 18.2.21 
    @types/react-dom: 18.2.14 => 18.2.14 
    @vercel/postgres: ^0.5.0 => 0.5.0 
    autoprefixer: 10.4.15 => 10.4.15 
    bcrypt: ^5.1.1 => 5.1.1 
    clsx: ^2.0.0 => 2.0.0 
    dotenv: ^16.3.1 => 16.3.1 
    next: ^14.0.0 => 14.0.0 
    postcss: 8.4.31 => 8.4.31 
    prettier: ^3.0.3 => 3.0.3 
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    tailwindcss: 3.3.3 => 3.3.3 
    typescript: 5.2.2 => 5.2.2 
    zod: ^3.22.2 => 3.22.4 
```

**Comment by alvaromagu** [comment]
I have the same issue with customers seed (using vercel database):
The code:
```javascript
async function seedCustomers () {
  try {
    await sql`CREATE EXTENSION IF NOT EXISTS "uuid-ossp"`

    // Create the "customers" table if it doesn't exist
    const createTable = await sql`
      CREATE TABLE IF NOT EXISTS customers (
        id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
        name VARCHAR(255) NOT NULL,
        email VARCHAR(255) NOT NULL,
        image_url VARCHAR(255) NOT NULL
      );
    `

    console.log('Created "customers" table')

    // Insert data into the "customers" table
    const insertedCustomers = await Promise.all(
      customers.map(
        async (customer) => await sql`
        INSERT INTO customers (id, name, email, image_url)
        VALUES (${customer.id}, ${customer.name}, ${customer.email}, ${customer.image_url})
        ON CONFLICT (id) DO NOTHING;
      `
      )
    )

    console.log(`Seeded ${insertedCustomers.length} customers`)

    return {
      createTable,
      customers: insertedCustomers
    }
  } catch (error) {
    console.error('Error seeding customers:', error)
    throw error
  }
}
```

And the error:
```
Error seeding customers: NeonDbError: db error: ERROR: prepared statement "s199509" does not exist

Caused by:
    ERROR: prepared statement "s199509" does not exist
    at execute (D:\dev\next\nextjs-dashboard\node_modules\.pnpm\@neondatabase+serverless@0.6.0\node_modules\@neondatabase\serverless\index.js:1539:48)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///D:/dev/next/nextjs-dashboard/scripts/seed.mjs:103:29
    at async Promise.all (index 6)
    at async seedCustomers (file:///D:/dev/next/nextjs-dashboard/scripts/seed.mjs:101:31)
    at async file:///D:/dev/next/nextjs-dashboard/scripts/seed.mjs:160:3 {
  code: '26000',
  sourceError: undefined
}
```

**Comment by vvo** [comment]
Hey there, our upstream provider (neon) had an issue and they are working on a fix. Will update this ticket.

**Comment by vvo** [comment]
Hey @johnsimeroth @aIv4ro this is now solved, sorry about that! Please comment if you're still having issues.
